# Generated by Django 5.0.1 on 2024-01-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
