# Generated by Django 5.0.1 on 2024-01-04 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0004_productbk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBK',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
