# Generated by Django 5.0.1 on 2024-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0006_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
