# Generated by Django 5.0.1 on 2024-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0012_alter_product_category_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottom_length',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dupata_length',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_length',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='washing',
            field=models.CharField(blank=True, choices=[(1, 'Dry-Clean'), (2, 'Easy Wash')], max_length=20, null=True),
        ),
    ]
