# Generated by Django 5.0.1 on 2024-01-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0013_alter_product_bottom_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Stiched'), ('2', 'Unstiched')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='washing',
            field=models.CharField(blank=True, choices=[('1', 'Dry-Clean'), ('2', 'Easy Wash')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ItemSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist_app.size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(through='productlist_app.ItemSizeCount', to='productlist_app.size'),
        ),
    ]
