# Generated by Django 5.0.1 on 2024-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0015_remove_product_countinstock_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsizecount',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='itemsizecount',
            name='size',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='stock',
            new_name='L',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.AddField(
            model_name='variant',
            name='M',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='S',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='XL',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='XXL',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ItemSizeCount',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
