# Generated by Django 5.0.1 on 2024-01-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0016_remove_itemsizecount_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='S',
            field=models.PositiveIntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
