# Generated by Django 5.0.1 on 2024-01-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0017_alter_product_item_code_alter_variant_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('1', 'Ethinic'), ('2', 'Party')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
