# Generated by Django 5.0.1 on 2024-01-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0019_product_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='video',
        ),
    ]
