# Generated by Django 5.0.1 on 2024-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0020_remove_variant_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
