# Generated by Django 5.0.1 on 2024-01-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0024_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
