# Generated by Django 5.0.1 on 2024-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0025_remove_variant_image_remove_variant_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
