# Generated by Django 5.0.1 on 2024-01-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0026_product_count_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
