# Generated by Django 5.0.1 on 2024-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0030_remove_order_createdat_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
