# Generated by Django 5.0.1 on 2024-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0032_occasion_alter_product_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('1', 'Ethinic'), ('2', 'Party'), ('0', '')], default=0, max_length=2, null=True),
        ),
    ]
