# Generated by Django 5.0.1 on 2024-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0035_delete_occasion_product_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('1', 'Ethinic'), ('2', 'Party'), ('0', '')], max_length=2, null=True),
        ),
    ]
