# Generated by Django 5.0.1 on 2024-02-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0037_remove_product_occasion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productlist_app.occasion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist_app.pattern'),
        ),
        migrations.AlterField(
            model_name='product',
            name='washing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist_app.washing'),
        ),
    ]
