# Generated by Django 5.0.1 on 2024-02-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist_app', '0039_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='occasion',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pattern',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pattern',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='washing',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='washing',
            name='video',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
